//! Module containing the deserialized representation of the config generated via the NixOS modules
//! system config for nimi

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use crate::process_manager::Service;

#[derive(Debug, Serialize, Deserialize)]
/// Representation of the nimi config generated by evaluating a nimi services module
///
/// Create this by using the nix package to run `nimi.evalServicesConfig`
pub struct Config {
    /// Deserialize representation of services
    pub services: HashMap<String, Service>,
}
